### ISSUE TITLE
KI100 (Physical Merge)

### ISSUE THREAD

**Issue by AndyFoy** [HabitatFramework/HLUTool#10]
##### Description

When a physical merge is performed in MapInfo (v8.0 and v10.5) the tool leaves MapInfo in an odd state.  The HLU polygon layer is no longer editable, and the newly merged polygon is set as the geoprocessing target.

See also KI94 and KI98.
##### Proposed Solution

May be related to how MapInfo is started.

**Comment by AndyFoy** [comment]
I propose closing this issue as it no longer appears to be a problem and numerous new versions have been released since this issue was first raised.

**Comment by drewlawson** [comment]
Hi Andy,

 

Fair enough!

 

Drew

**Comment by AndyFoy** [comment]
Closed as this issue no longer appears to be a problem and numerous new versions have been released since this issue was first raised.
