### ISSUE TITLE
CR40 (Physical merge prompt)

### ISSUE THREAD

**Issue by AndyFoy** [HabitatFramework/HLUTool#61]
##### Description

When the user performs a logical merge of two features from the same TOID the user is prompted to ‘Perform physical merge as well?’ together with ‘Yes’ or ‘No’ buttons.

Furthermore, the default action on the prompt is ‘No’ so the user must select the ‘Yes’ button using the mouse rather than being able to press <Enter> on their keyboard.
##### Proposed Solution

Amend the tool so that the user can specify in the options form whether a physical merge should be performed following a logical merge of two features from the same TOID by offering the options ‘Always’, ‘Never’ or ‘Prompt’. Amend the tool to automatically perform the selected action (as appropriate). If the selected option is ‘Prompt’ then ensure the default button on the existing prompt is ‘Yes’.

**Comment by AndyFoy** [comment]
The solution to this change is not as simple as first proposed because the tool will also need to determine if the features that have been logically merge are also adjacent to one another (to avoid the likelihood of physically merging spatially separate features).  It is unknown if any LERCs would like this feature to be developed at this stage.

Please indicate if you would like this change request developed - otherwise I propose that this change is closed.

**Comment by bconeybeer** [comment]
I don't get a physical merge prompt when logically merging from the same TOID - all that happens is the merge icon at the top of the interface lights up green to show two features can be physically merged. Happy for you to close this one.

**Comment by drewlawson** [comment]
Doesn't sound like it's worth effort at this stage

**Comment by AndyFoy** [comment]
Closed as no LERCs would like this feature to be developed at this stage.
