### ISSUE TITLE
CR41 (Potential BAP Habitats)

### ISSUE THREAD

**Issue by AndyFoy** [HabitatFramework/HLUTool#62]
##### Description

Currently the tool will only support BAP habitats with a determination quality other than ‘Not present but close to’ when they are reflected in the associated feature(s) by the relevant IHS codes. However, there may be situations with some sites where a number of BAP habitats are known or thought to exist but the site can’t be separated into distinct features that each reflects a single set of IHS codes (each representing one or more BAP habitats).

For example, some SSSI sites can be mapped in multiple national inventories using the whole SSSI boundary rather than representing the distinct area for each BAP habitat in each relevant inventory. It is therefore currently not possible to represent an entire SSSI feature using the HLU Tool where multiple BAP Habitats are present.
##### Proposed Solution

Amend the tool so that ‘Potential BAP Habitats’ can be added where their determination quality can also be **‘Habitat is in polygon, but not accurately mappable’** or **‘Habitat probably in polygon, but not accurately mappable’**.

Also amend the tool user interface to:
i. Rename the **_‘BAP Habitats’**_ heading to **_‘Primary BAP Habitats’**_.
ii. Rename the **_‘Potential BAP Habitats’**_ heading to **‘Secondary BAP Habitats’***.

**Comment by AndyFoy** [comment]
It is unknown if any LERCs would like this feature to be developed at this stage.  Please indicate if you would like this change request developed - otherwise I propose that this change is closed.

**Comment by bconeybeer** [comment]
I would say this isn't so important to HBIC at this stage as we map sites to enough detail that priority habitats can be listed in the conventional way; also the term 'potential' BAP habitats is good for those sites that are being developed for a certain habitat but too 'young' to qualify (e.g. developing chalk grassland); 'secondary' would be misleading here.

**Comment by GrahamHawker** [comment]
We are ignoring the whole potential BAP habitats stuff and won't use it. I'm happy as long as it doesn't interfere with anything else or demand that things get filled in.

**Comment by drewlawson** [comment]
Doesn't sound like a high priority issue at present

**Comment by AndyFoy** [comment]
Closed as no LERCs would like this feature to be developed at this stage.
