### ISSUE TITLE
KI114 (Split/Merge errors)

### ISSUE THREAD

**Issue by AndyFoy** [HabitatFramework/HLUTool#68]
##### Description

Random split & merge issues using MapInfo and Access database.

See comments on KI100.

This may be caused by one or more of the following:
• An error in the HLU Tool
• Using an Access database
• A combination of using MapInfo and an Access database
• The integrity of the HLU data
##### Proposed Solution

Unknown what the cause is or the extent of the problems.  May need to debug tool whilst user performs splits/merges.

**Comment by AndyFoy** [comment]
I propose closing this issue as it no longer appears to be a problem and numerous new versions have been released since this issue was first raised.

**Comment by GrahamHawker** [comment]
I haven't seen this issue in recent versions.

**Comment by AndyFoy** [comment]
Closed as this issue no longer appears to be a problem and numerous new versions have been released since this issue was first raised.
