### ISSUE TITLE
KI115 (Database update failures)

### ISSUE THREAD

**Issue by AndyFoy** [HabitatFramework/HLUTool#69]
##### Description

On some occasions the tool reports that updates to the database tables have failed, even though they may (or may not) have actually succeeded. Most commonly it is updates to the **History** table that are reported as failed.
##### Proposed Solution

Unknown what the cause or extent of the problem is - it may only be happening when using the tool with MapInfo. Will need to debug the tool to identify the cause of the problem or, failing that, improve the error reporting to help determine the underlying cause.

**Comment by GrahamHawker** [comment]
I haven't noticed this sort of problem in recent versions.

**Comment by drewlawson** [comment]
SxBRC not used tool sufficiently to comment!

**Comment by AndyFoy** [comment]
Closed as this issue no longer appears to be a problem and numerous new versions have been released since this issue was first raised.
