### ISSUE TITLE
CR43 (Sort multiple fields in exports)

### ISSUE THREAD

**Issue by AndyFoy** [HabitatFramework/HLUTool#70]
##### Description #####
Currently, when exporting features to a new GIS layer, if there are multiple fields from the same 'child' table (i.e. matrix, formation, management, complex, bap or source fields) in the export format then the order the fields appear in the GIS layer is random.  For example, if there are two matrix codes assigned to an incid they can appear in either order as matrix1 or matrix2 in the exported layer.

##### Proposed Solution #####
Sort all records from 'child' tables so that multiple fields will always appear in the same order in exported layers.  The order will be as follows:

* **Matrix**, **Formation**, **Management** and **Complex** IHS codes will be output in the order they were added to an incid (which is the same order they appear in the tool user interface 'IHS' tab).
* *True* (i.e. not 'None') **Priority Habitats** will be output in the order they were added to an incid, and within these 'primary' habitats (automatically added based on the IHS codes) will be output before 'secondary' habitats.
* *False* (i.e. 'None') **Priority Habitats** will be output only after any True habitats have been output.
* **Sources** will be output in the order they appear in the tool user interface 'Sources' tab (i.e. Source1 then Source2 then Source3).

**Comment by Wolfgang-HBIC** [comment]
Works for us at HBIC.
