### ISSUE TITLE
KI116 (Cancelled attribute updates)

### ISSUE THREAD

**Issue by AndyFoy** [HabitatFramework/HLUTool#72]
##### Description

When an attempt is made to update a polygon/subset of an INCID with multiple polygons, a warning dialogue “**Attempting to update subset of Incid**” appears giving the option to either logically split the selected subset before applying the update (by clicking ‘Yes’), to apply the update to all polygons of that Incid (by clicking ‘No’), or to cancel. When pressing 'Cancel',  a warning appears stating the update was cancelled and no updates where applied, however, the update is indeed applied to all polygons of the same INCID and a history recorded.
##### Proposed Solution

Try and re-create the issue under debug conditions to identify the cause (in theory according to the code this is not possible).  Resolve the issue once identified.

**Comment by GrahamHawker** [comment]
I have tried this with MapInfo version and this bug doesn't happen for me. Cancelling works fine.

**Comment by bconeybeer** [comment]
Perhaps this is an ArcGIS problem? It still happens with the latest version of the tool with me.

**Comment by drewlawson** [comment]
SxBRC not in a position to comment as haven't used HLU Tool sufficiently as yet.  But we are ArcGIS users and if this is specific to ArcGIS, then happy to support a fix.

**Comment by AndyFoy** [comment]
Fixed in v3.0.0.
