### ISSUE TITLE
KI117 (Bulk update errors)

### ISSUE THREAD

**Issue by AndyFoy** [HabitatFramework/HLUTool#73]
##### Description

When applying updates in **Bulk Update** mode an error occurred indicating that the 'Determination Quality' was missing despite a value being supplied.  Also reports of Source data not being updated.
##### Proposed Solution

Run a series of tests in Bulk Update mode to try and re-create the error.  Then identify and resolve the error.

**Comment by GrahamHawker** [comment]
This is an error I had and it certainly is high priority for fixing to use the tool easily.

**Comment by bconeybeer** [comment]
I don't remember determination quality being a particular issue when we carried out a bulk update last year.

**Comment by drewlawson** [comment]
Don't have any experience of bulk updates as yet but happy to support a fix if this is a fundamental issue.

**Comment by AndyFoy** [comment]
Considered fixed in v3.0.0.

**Comment by AndyFoy** [comment]
Fixed in v3.0.0.
